name: Georg Klauda
title: Georg Klauda
description: Soziologe & Webentwickler

tags:
  - LGBT
  - Queer
  - Geschichte
  - Politik
  - Islam
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Kontakt
    url: /contact
  - title: Feed
    url: /feed.xml
email: georg.klauda@gmail.com
# See: https://disqus.com/
# disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: mqkjknng
