date_format: "%d.%m.%Y"
formspree_form_id: mqkjknng
name: Georg Klauda
title: Georg Klauda | Soziologe, Autor &amp; VueJS Developer
description: Bücher, Essays und Rezensionen zu queeren und rassismuskritischen Themen
tags:
  - LGBT
  - Queer
  - Geschichte
  - Politik
  - Islam
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Kontakt
    url: /contact
  - title: Web projects
    url: /web-projects
  - title: Feed
    url: /feed.xml
email: georg.klauda@gmail.com
